### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by arjunmenon** [lorenzoongithub/completely#1]
hey
nice script. but can be made more user friendly if tab selection is also there.

any case. great work.

**Comment by lorenzoongithub** [comment]
Thanks for your comment. 
I need to think on this on this one. 
Overriding the tab behaviour might not be something user wants as the "tab" key is used to move on 'focusable' HTML elements. However, I think you might be right if the user hits the tab when a hint is displayed... again I will think on this one...
cheers

**Comment by skmasq** [comment]
If this could be implemented I would use this library in a snap.

What I'm thinking adding an option to use tab autocomplete or space autocomplete depending what user want's.

E.g.

> I type "I"
> Suggestion "I need code"
> Input is locked with tab
> User tabs and autocompletes
> Tab is unlocked

So basically when user is starting to type TAB is locked in that input.

Looking forward with this library very, very promising.

**Comment by lorenzoongithub** [comment]
Fair enough. I will take a look.
As said, it seems a very reasonable request.

**Comment by emilwall** [comment]
+1. This is extra important when there is only one suggestion, I can't find a way to do auto-complete then. Tab, space or enter are the natural alternatives. Ctrl+space might work as an unobtrusive approach, but few would realize that it can be used.

I vote for tab completion, and a possibility to disable it for one keypress (and temporarily remove the auto-complete proposal) by clicking ESC.

**Comment by lorenzoongithub** [comment]
I am going to upload complete.ly.1.0.1  This new version will have only one change: the ability to handle 'tabs'. Its behaviour should be as discussed. If you guys are okay with it I will then close the issue.

**Comment by lorenzoongithub** [comment]
closing it.

**Comment by arjunmenon** [comment]
tabs feature makes it more intuitive. thanks.

one more thing, what if i have to edit or make a new choice after tabbing. currently, i have to delete the whole sentence then start over again. is there a better way?

**Comment by lorenzoongithub** [comment]
Hi Ariun, I am not sure if I understand your new question. Once you make a choice you could use the back-space until new options are available. For instance you choose 'apple' then you press backspace 'appl' and again ('app') and again and once you get 'ap' the option 'apricot' will be also available. 
Is not that what you are talking about ? Please open a new issue if you feel like and try to describe it as accurately as you can.  cheers

**Comment by BDhara** [comment]
I am getting an error at document.body.appendChild(prompt); line that body is null..please help me..I want to use it for div contenteditable tag..
