### ISSUE TITLE
support input-text-fields

### ISSUE THREAD

**Issue by trendschau** [lorenzoongithub/completely#19]
Thank you for this beautiful small script!
A native support of input-text-fields instead of divs would be nice. I am aware of this http://stackoverflow.com/questions/20317234/use-complete-ly-with-a-input-text-box, but next you have to listen to the return event and so on. With a support of input-text-field it would be easier to use the script for a search-field.

**Comment by lorenzoongithub** [comment]
Fair point.. But, in my mind, that would be a whole different implementation.. 
Thanks for the feedback anyway
