### ISSUE TITLE
non-minified source missing in repository

### ISSUE THREAD

**Issue by iki** [lorenzoongithub/completely#2]
would be quite difficult to track changes ;)

**Comment by lorenzoongithub** [comment]
iki, I think you are mistaken. Minified and non-minified code are available.

http://lorenzoongithub.github.io/completely/complete.ly.1.0.0.js
http://lorenzoongithub.github.io/completely/complete.ly.1.0.0.min.js

**Comment by iki** [comment]
Right, the **release** files are on http://lorenzoongithub.github.io/completely via the [gh_pages branch](https://github.com/lorenzoongithub/completely/tree/gh-pages), which is OK.

What I meant is that most projects do development in [master branch](https://github.com/lorenzoongithub/completely/tree/master) (or some other branch based on their process), track all changes between releases here, accept PR's, etc. The source `complete.ly.js` should be placed. The `.min.js` file was there instead before a7db4de5fd8a30e36ebeabe1b29762b1b9bdeba6.

**Comment by lorenzoongithub** [comment]
iki, in a way you are right and many projects in GitHub have a more elegant and transparent structure. No doubt, for my little project I chose to try an approach that fits more my way of thinking and let GitHub be just a place to store the code.
