### ISSUE TITLE
onEnter does not fire

### ISSUE THREAD

**Issue by FND** [lorenzoongithub/completely#21]
as far as I can tell, the `onEnter` event handler is never invoked because the dropdown visibility check (`var wasDropDownHidden = (dropDown.style.visibility == 'hidden');`) occurs just before the dropdown is actually hidden

**Comment by lorenzoongithub** [comment]
mmmhhh, I think onEnter works. create jsfiddle to demonstrate otherwise 
cheers

**Comment by lborgman** [comment]
Maybe it is a problem with when `onEnter` should fire? Should it fire when an item in the dropdown is selected? Or should it fire only on `CR` when dropdown is not visible?
