### ISSUE TITLE
Have method, that turns off complete.ly

### ISSUE THREAD

**Issue by pmapcat** [lorenzoongithub/completely#24]
I think, in specific cases, there would be good to have possibility to turn off the plugin. 
(Like in react componentDidMount,componentWillUnmount, to prevent leakage).

**Comment by lorenzoongithub** [comment]
@VbifRkbvjd
Turning off complete.ly might mean different things.
If you mean "turning off autocompletion" then all you have to do is let that happen 

e.g write something like this:
 <code> 
 pv.onChange = function() { pv.options=[]; pv.repaint(); }
</code>

if turning off means disabling the underlying input text then you have to write something like this:
<code>
pv.input.disabled='disabled'
</code>
