### ISSUE TITLE
Fuzzy Search?

### ISSUE THREAD

**Issue by chelder86** [lorenzoongithub/completely#29]
Actually nice library! Unfortunately I think I can't use it in my case.

For example, if the words are:
- Red car
- Blue crystal cycle

If we type "cycle", it won't select "Blue cycle". It won't select anything.

Anyway thanks for your library!

Carlos

**Comment by lorenzoongithub** [comment]
Your proposal is way too hard. Maybe there is an alternative solution.
In your array of options have "Red car" as well as "car - Red Car", 
"Blue crystal Cycle", "Cycle Blue Cristal" and so on.
Not all the permutations. Just what you think it makes sense.
It should work

**Comment by chelder86** [comment]
okayy.
Just if it helps. Ugly documented, but it seems that here is implemented: http://www.somacon.com/p241.php

**Comment by chelder86** [comment]
Here is my code so far based on the previous code: http://jsfiddle.net/chelder86/7d941wrL/

It is short and without external dependencies. So I think it eventually could be useful for you. Anyway I'm asking about suggestion to improve it here: http://stackoverflow.com/questions/28822968/creating-my-own-datalist-to-search-within-an-autofill-combobox-with-javascript-w
