### ISSUE TITLE
any way to modify a part of a sentence.

### ISSUE THREAD

**Issue by arjunmenon** [lorenzoongithub/completely#3]
hey
thanks for the tab feature. now, what if you had to modify the statement that you had chosen. for example, like
i need a flight from london to paris.

now if i had to choose a train, presently, i have to delete the sentence completely, then type and choose the train option, and go over again choosing the places.

what if there is a way to just click on "i need a flight", dropdown appears, choose that particular option, and ur done, without starting again to choose the places.

thanks.

**Comment by lorenzoongithub** [comment]
Hey ariun,
if you are unhappy of what you typed you should hit backspace. As you remove characters new options might become available. if that is too slow, you could build other HTML elements around to help you ? For instance you could have a button that once clicked we set the text of completely to "I need a train " regardless of the existing text... is this satisfactory ? or am I misunderstanding you ? are you saying that editing text in the middle of a sentence does not provide autocompletion ?

**Comment by lorenzoongithub** [comment]
no further feedback. closing it then.
