### ISSUE TITLE
Unable to support case-insensitive search

### ISSUE THREAD

**Issue by apratheek** [lorenzoongithub/completely#30]
Hi, I'm new to JS, so I'm not sure if this is an issue with your library itself. I'm trying to perform a case-insensitive search on my webpage and seems to me that completely doesn't support it (or I might be doing it wrong). Could you help me out?

**Comment by lorenzoongithub** [comment]
Hi apratheek,
It is not an issue; however, if you want complete.ly to ignore the case you need to make sure that you handle that yourself. Remember you need to register for notifications then once you know the string that the user is typing you can call .toLowerCase() and decide what the array of options might look like. 

cheers

**Comment by apratheek** [comment]
Hi Lorenzo,

Thank you for your reply. I guess your logic makes a whole lot of sense. Regarding JS, I'm a noob. I appreciate you helping me out here.

Sincerely,
Pratheek Adidela

-----Original Message-----
