### ISSUE TITLE
there is no code here and I would like to make a pull request. :-(

### ISSUE THREAD

**Issue by mdipierro** [lorenzoongithub/completely#31]

**Comment by lorenzoongithub** [comment]
@mdipierro sadly, you are right. there is no much to pull.
Yet the code is fully available so if you want to go ahead and modify go for it.
Best

**Comment by mdipierro** [comment]
Sei Italiano? Come mai il codice non e' su github? E' una bella librereria.

**Comment by lorenzoongithub** [comment]
Si. Il codice e' qui: http://lorenzoongithub.github.io/completely/complete.ly.1.0.1.js
Non ho tempo per mantenere il codice. grazie ciao.
