### ISSUE TITLE
How to pass variables via submit button?

### ISSUE THREAD

**Issue by electroze** [lorenzoongithub/completely#5]
Hello, I like your lightweight script. My obstacle is I don't know the $variable name of the field? I've added a submit button and wrapped it with an html form, which I'm sending as a GET request to another page with the variable q=searched word. But how do I make $q = what the user types in completely? Thank you.

**Comment by lorenzoongithub** [comment]
@electroze this is a question not an issue. I would need more information to help you but I would suggest you use stackoverflow for it http://stackoverflow.com/questions/tagged/complete.ly
