### ISSUE TITLE
Code missing

### ISSUE THREAD

**Issue by chemix** [lorenzoongithub/completely#6]
Hi, why you don't have code of complete.ly.1.0.1.js on github?

**Comment by lorenzoongithub** [comment]
@chemix 
The code is on GitHub  
http://lorenzoongithub.github.io/completely/complete.ly.1.0.1.js
cheers

**Comment by chemix** [comment]
@lorenzoongithub yes,
but what i missing is file like: https://github.com/lorenzoongithub/completely/src/completely.js  in main repository

btw: i'm playing whit lib and look great, simple and powerfull
