### ISSUE TITLE
Escaping the hint list

### ISSUE THREAD

**Issue by mattpass** [lorenzoongithub/completely#8]
I have a suggestion re the UI (hope it's OK to post here, your site asks for suggestions to be logged on GitHub). :)

The norm for escaping a form select list in browsers includes pressing Esc or clicking away from the list. However, complete.ly doesn't seem to handle that and the list remains in view. Would be great to replicate the same UI escaping.

On a similar note, would be great if users could press Tab (or shift+Tab) to move onto the next form field (or back to a previous). It's great that users can hit Tab or Enter to use the hint value, but then hitting Tab keeps focus on complete.ly.

**Comment by lorenzoongithub** [comment]
tab keeps the focus on the widget if there was the popup window. Otherwise it moves to the next focusable HTML component. 
Defining the right behaviour for Tab and ESC was quite a challenge. I pretty much copied the way it works in the Chrome console.
